export const products = {
  mobile: [
    {
      id: 1,
      name: "iPhone 15 Pro",
      price: 999,
      image: "/iphone-15-pro.png",
      description: "Latest iPhone with A17 Pro chip and titanium design",
      category: "mobile",
      specifications: ["6.1-inch display", "A17 Pro chip", "48MP camera", "128GB storage"],
    },
    {
      id: 2,
      name: "Samsung Galaxy S24",
      price: 899,
      image: "/samsung-galaxy-s24-smartphone.jpg",
      description: "Flagship Android phone with AI features",
      category: "mobile",
      specifications: ["6.2-inch display", "Snapdragon 8 Gen 3", "50MP camera", "256GB storage"],
    },
    {
      id: 3,
      name: "Google Pixel 8",
      price: 699,
      image: "/google-pixel-8-smartphone.jpg",
      description: "Pure Android experience with excellent camera",
      category: "mobile",
      specifications: ["6.2-inch display", "Google Tensor G3", "50MP camera", "128GB storage"],
    },
    {
      id: 4,
      name: "OnePlus 12",
      price: 799,
      image: "/oneplus-12-smartphone.jpg",
      description: "Fast charging flagship with premium design",
      category: "mobile",
      specifications: ["6.82-inch display", "Snapdragon 8 Gen 3", "50MP camera", "256GB storage"],
    },
    {
      id: 5,
      name: "Xiaomi 14",
      price: 649,
      image: "/xiaomi-14-smartphone.png",
      description: "High-performance phone with great value",
      category: "mobile",
      specifications: ["6.36-inch display", "Snapdragon 8 Gen 3", "50MP camera", "256GB storage"],
    },
    {
      id: 6,
      name: "iPhone 14",
      price: 799,
      image: "/iphone-14-smartphone.png",
      description: "Reliable iPhone with great camera system",
      category: "mobile",
      specifications: ["6.1-inch display", "A15 Bionic chip", "48MP camera", "128GB storage"],
    },
    {
      id: 7,
      name: "Samsung Galaxy A54",
      price: 449,
      image: "/samsung-galaxy-a54.png",
      description: "Mid-range phone with premium features",
      category: "mobile",
      specifications: ["6.4-inch display", "Exynos 1380", "50MP camera", "128GB storage"],
    },
    {
      id: 8,
      name: "Nothing Phone 2",
      price: 599,
      image: "/nothing-phone-2-smartphone.jpg",
      description: "Unique design with transparent back",
      category: "mobile",
      specifications: ["6.7-inch display", "Snapdragon 8+ Gen 1", "50MP camera", "256GB storage"],
    },
    {
      id: 9,
      name: "Motorola Edge 40",
      price: 549,
      image: "/motorola-edge-40-smartphone.jpg",
      description: "Curved display with clean Android",
      category: "mobile",
      specifications: ["6.55-inch display", "MediaTek Dimensity 8020", "50MP camera", "256GB storage"],
    },
    {
      id: 10,
      name: "Realme GT 5",
      price: 499,
      image: "/realme-gt-5-smartphone.jpg",
      description: "Gaming-focused phone with fast performance",
      category: "mobile",
      specifications: ["6.74-inch display", "Snapdragon 8 Gen 2", "50MP camera", "256GB storage"],
    },
    {
      id: 11,
      name: "Oppo Find X6",
      price: 749,
      image: "/oppo-find-x6-smartphone.jpg",
      description: "Camera-centric flagship with Hasselblad partnership",
      category: "mobile",
      specifications: ["6.74-inch display", "Snapdragon 8 Gen 2", "50MP camera", "256GB storage"],
    },
    {
      id: 12,
      name: "Vivo X90",
      price: 699,
      image: "/vivo-x90-smartphone.jpg",
      description: "Photography flagship with Zeiss optics",
      category: "mobile",
      specifications: ["6.78-inch display", "MediaTek Dimensity 9200", "50MP camera", "256GB storage"],
    },
  ],
  tv: [
    {
      id: 13,
      name: 'Samsung 65" QLED 4K',
      price: 1299,
      image: "/samsung-qled-4k-tv-65-inch.jpg",
      description: "Premium QLED TV with quantum dot technology",
      category: "tv",
      specifications: ["65-inch display", "4K resolution", "HDR10+", "Smart TV features"],
    },
    {
      id: 14,
      name: 'LG 55" OLED C3',
      price: 1199,
      image: "/lg-oled-c3-tv-55-inch.jpg",
      description: "OLED TV with perfect blacks and vibrant colors",
      category: "tv",
      specifications: ["55-inch display", "4K OLED", "Dolby Vision", "webOS smart platform"],
    },
    {
      id: 15,
      name: 'Sony 75" Bravia XR',
      price: 1899,
      image: "/sony-bravia-xr-tv-75-inch.jpg",
      description: "Large screen TV with cognitive processor",
      category: "tv",
      specifications: ["75-inch display", "4K LED", "XR processor", "Google TV"],
    },
    {
      id: 16,
      name: 'TCL 50" QLED',
      price: 599,
      image: "/tcl-qled-tv-50-inch.jpg",
      description: "Affordable QLED with great picture quality",
      category: "tv",
      specifications: ["50-inch display", "4K QLED", "HDR10", "Roku TV"],
    },
    {
      id: 17,
      name: 'Hisense 65" ULED',
      price: 799,
      image: "/hisense-uled-tv-65-inch.jpg",
      description: "ULED technology with quantum dot color",
      category: "tv",
      specifications: ["65-inch display", "4K ULED", "Dolby Vision", "VIDAA smart OS"],
    },
    {
      id: 18,
      name: 'Philips 55" Ambilight',
      price: 899,
      image: "/philips-ambilight-tv-55-inch.jpg",
      description: "Unique Ambilight technology for immersive viewing",
      category: "tv",
      specifications: ["55-inch display", "4K LED", "Ambilight", "Android TV"],
    },
    {
      id: 19,
      name: 'Panasonic 65" OLED',
      price: 1399,
      image: "/panasonic-oled-tv-65-inch.jpg",
      description: "Professional-grade OLED with accurate colors",
      category: "tv",
      specifications: ["65-inch display", "4K OLED", "HDR10+", "My Home Screen"],
    },
    {
      id: 20,
      name: 'Xiaomi 43" 4K',
      price: 349,
      image: "/xiaomi-4k-tv-43-inch.jpg",
      description: "Budget-friendly 4K TV with smart features",
      category: "tv",
      specifications: ["43-inch display", "4K LED", "HDR10", "Android TV"],
    },
    {
      id: 21,
      name: 'Sharp 70" Aquos',
      price: 999,
      image: "/sharp-aquos-tv-70-inch.jpg",
      description: "Large screen TV with Aquos technology",
      category: "tv",
      specifications: ["70-inch display", "4K LED", "HDR", "Roku TV"],
    },
    {
      id: 22,
      name: 'Toshiba 55" Fire TV',
      price: 449,
      image: "/placeholder.svg?height=300&width=300",
      description: "Smart TV with built-in Fire TV experience",
      category: "tv",
      specifications: ["55-inch display", "4K LED", "HDR10", "Fire TV built-in"],
    },
    {
      id: 23,
      name: 'JVC 65" 4K',
      price: 699,
      image: "/placeholder.svg?height=300&width=300",
      description: "Reliable 4K TV with good picture quality",
      category: "tv",
      specifications: ["65-inch display", "4K LED", "HDR", "Smart TV features"],
    },
    {
      id: 24,
      name: 'Insignia 50" Fire TV',
      price: 399,
      image: "/placeholder.svg?height=300&width=300",
      description: "Budget Fire TV with essential smart features",
      category: "tv",
      specifications: ["50-inch display", "4K LED", "HDR10", "Fire TV Edition"],
    },
  ],
  tablet: [
    {
      id: 25,
      name: 'iPad Pro 12.9"',
      price: 1099,
      image: "/placeholder.svg?height=300&width=300",
      description: "Professional tablet with M2 chip",
      category: "tablet",
      specifications: ["12.9-inch display", "M2 chip", "128GB storage", "Apple Pencil support"],
    },
    {
      id: 26,
      name: "Samsung Galaxy Tab S9",
      price: 799,
      image: "/placeholder.svg?height=300&width=300",
      description: "Premium Android tablet with S Pen",
      category: "tablet",
      specifications: ["11-inch display", "Snapdragon 8 Gen 2", "128GB storage", "S Pen included"],
    },
    {
      id: 27,
      name: "iPad Air",
      price: 599,
      image: "/placeholder.svg?height=300&width=300",
      description: "Versatile tablet for work and creativity",
      category: "tablet",
      specifications: ["10.9-inch display", "M1 chip", "64GB storage", "Touch ID"],
    },
    {
      id: 28,
      name: "Microsoft Surface Pro 9",
      price: 999,
      image: "/placeholder.svg?height=300&width=300",
      description: "2-in-1 tablet that replaces your laptop",
      category: "tablet",
      specifications: ["13-inch display", "Intel Core i5", "128GB SSD", "Type Cover compatible"],
    },
    {
      id: 29,
      name: "Lenovo Tab P11 Pro",
      price: 449,
      image: "/placeholder.svg?height=300&width=300",
      description: "OLED tablet with premium design",
      category: "tablet",
      specifications: ["11.5-inch OLED", "MediaTek Kompanio 1300T", "128GB storage", "Precision Pen 3"],
    },
    {
      id: 30,
      name: "Amazon Fire HD 10",
      price: 149,
      image: "/placeholder.svg?height=300&width=300",
      description: "Budget-friendly tablet for entertainment",
      category: "tablet",
      specifications: ["10.1-inch display", "Octa-core processor", "32GB storage", "Alexa built-in"],
    },
    {
      id: 31,
      name: "Huawei MatePad Pro",
      price: 699,
      image: "/placeholder.svg?height=300&width=300",
      description: "Professional tablet with M-Pencil support",
      category: "tablet",
      specifications: ["12.6-inch display", "Kirin 9000E", "128GB storage", "M-Pencil support"],
    },
    {
      id: 32,
      name: "Xiaomi Pad 6",
      price: 399,
      image: "/placeholder.svg?height=300&width=300",
      description: "High-performance tablet with great value",
      category: "tablet",
      specifications: ["11-inch display", "Snapdragon 870", "128GB storage", "Dolby Vision"],
    },
    {
      id: 33,
      name: "ASUS ZenPad 3S",
      price: 329,
      image: "/placeholder.svg?height=300&width=300",
      description: "Compact tablet with premium build",
      category: "tablet",
      specifications: ["9.7-inch display", "MediaTek MT8176", "64GB storage", "ZenUI interface"],
    },
    {
      id: 34,
      name: "OnePlus Pad",
      price: 479,
      image: "/placeholder.svg?height=300&width=300",
      description: "Fast and smooth tablet experience",
      category: "tablet",
      specifications: ["11.61-inch display", "MediaTek Dimensity 9000", "128GB storage", "OxygenOS"],
    },
    {
      id: 35,
      name: "Realme Pad 2",
      price: 249,
      image: "/placeholder.svg?height=300&width=300",
      description: "Affordable tablet with good performance",
      category: "tablet",
      specifications: ["11.5-inch display", "MediaTek Helio G99", "128GB storage", "Realme UI"],
    },
    {
      id: 36,
      name: "Nokia T21",
      price: 199,
      image: "/placeholder.svg?height=300&width=300",
      description: "Reliable tablet with clean Android",
      category: "tablet",
      specifications: ["10.36-inch display", "Unisoc Tiger T612", "64GB storage", "Stock Android"],
    },
  ],
}

export const getProductsByCategory = (category) => {
  return products[category] || []
}

export const getProductById = (id) => {
  const allProducts = [...products.mobile, ...products.tv, ...products.tablet]
  return allProducts.find((product) => product.id === Number.parseInt(id))
}

export const getAllProducts = () => {
  return [...products.mobile, ...products.tv, ...products.tablet]
}
